name: ExUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: ExUnit Tests
    runs-on: [ubuntu-20.04]
    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: ['1.12.3', '1.13.1']
        otp: ['24.1']
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Cache Dependency Sources
      uses: actions/cache@v2
      id: deps-cache
      with:
        path: deps
        # If you ever need to clear the cache, increment the number after "v1" here
        key: dependencies-v1-${{matrix.elixir}}-${{ hashFiles('**/mix.lock') }}
        restore-keys: dependencies-${{ hashFiles('**/mix.lock') }}
    - name: Cache Compiled Files
      uses: actions/cache@v2
      with:
        path: _build/test/
        key: compiled-test-${{matrix.elixir}}-${{ hashFiles('**/mix.lock') }}
        restore-keys: compiled-test-${{matrix.elixir}}
    # In my experience, I have issues with incremental builds maybe 1 in 100
    # times that are fixed by doing a full recompile.
    # In order to not waste dev time on such trivial issues (while also reaping
    # the time savings of incremental builds for *most* day-to-day development),
    # I force a full recompile only on builds that we retry.
    - name: Clean
      if: github.run_attempt != '1'
      run: | 
        mix deps.clean --all
        mix clean
    - name: Install Dependencies
      run: mix deps.get
    - name: Build
      run: mix compile --all-warnings --warnings-as-errors
    # If the compile fails, it's likely due to a warning. Go ahead and run the tests
    # to give the devs feedback and save them some time.
    - name: Run Tests
      # You might consider adding the --stale flag here as well.
      # Doing so will cause Mix to attempt to run only the tests that reference modules
      # that have changed since the last CI run.
      # https://hexdocs.pm/mix/1.12/Mix.Tasks.Test.html#module-the-stale-option
      run: mix test
      if: always()

    # TODO: Log test coverage
